# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=20)),
                ('heroname', models.CharField(max_length=20)),
                ('heroinname', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
